export const countryOptions = [
  { value: '1', label: '🇺🇸 United States' },
  { value: '44', label: '🇬🇧 United Kingdom' },
  { value: '49', label: '🇩🇪 Germany' },
  { value: '33', label: '🇫🇷 France' },
  { value: '81', label: '🇯🇵 Japan' },
  { value: '86', label: '🇨🇳 China' },
  { value: '91', label: '🇮🇳 India' },
  { value: '7', label: '🇷🇺 Russia' },
  { value: '55', label: '🇧🇷 Brazil' },
  { value: '27', label: '🇿🇦 South Africa' },
  { value: '234', label: '🇳🇬 Nigeria' },
  { value: '20', label: '🇪🇬 Egypt' },
  { value: '92', label: '🇵🇰 Pakistan' },
  { value: '880', label: '🇧🇩 Bangladesh' },
  { value: '62', label: '🇮🇩 Indonesia' },
  { value: '52', label: '🇲🇽 Mexico' },
  { value: '34', label: '🇪🇸 Spain' },
  { value: '39', label: '🇮🇹 Italy' },
  { value: '82', label: '🇰🇷 South Korea' },
  { value: '61', label: '🇦🇺 Australia' },
  { value: '1', label: '🇨🇦 Canada' },
  { value: '41', label: '🇨🇭 Switzerland' },
  { value: '46', label: '🇸🇪 Sweden' },
  { value: '47', label: '🇳🇴 Norway' },
  { value: '45', label: '🇩🇰 Denmark' },
  { value: '358', label: '🇫🇮 Finland' },
  { value: '31', label: '🇳🇱 Netherlands' },
  { value: '32', label: '🇧🇪 Belgium' },
  { value: '43', label: '🇦🇹 Austria' },
  { value: '353', label: '🇮🇪 Ireland' },
  { value: '64', label: '🇳🇿 New Zealand' },
  { value: '351', label: '🇵🇹 Portugal' },
  { value: '30', label: '🇬🇷 Greece' },
  { value: '90', label: '🇹🇷 Turkey' },
  { value: '972', label: '🇮🇱 Israel' },
  { value: '971', label: '🇦🇪 UAE' },
  { value: '966', label: '🇸🇦 Saudi Arabia' },
  { value: '65', label: '🇸🇬 Singapore' },
  { value: '852', label: '🇭🇰 Hong Kong' },
  { value: '886', label: '🇹🇼 Taiwan' },
];
